### ISSUE TITLE
Stretched images in News items

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-website-rebuild#100]
![screen shot 2018-03-01 at 2 42 42 pm 2](https://user-images.githubusercontent.com/36524570/36826014-e33054fa-1d5e-11e8-90ee-4f954b59915c.png)

Hero images are appearing slightly stretched vertically when placed into news items. All ratios are the same.

**Comment by imperator99** [comment]
Hey @nicolakcoady I haven't styled up these pages yet so they'll look ugly until that happens :-)
