### ISSUE TITLE
A better way to add images to content

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#1015]
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What is the context for your issue or request?

Given I am a content editor

# What action do you want to take within that context?

When I am adding new content or editing existing content
And I add an image to the body content

# What do you expect to happen when you take that action?

Then I should be able to add alt text and a caption through the user interface, without having to use HTML.
And image tags should automatically use `<figure>` and `<figcaption>`

**Comment by KiriHoy** [comment]
fixed in #1034
