### ISSUE TITLE
Allow related content links to link to external pages

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#103]
Not sure about the best technical solution is but for example:

we need to have a related content card on the guides and tools page that links straight to guides, content guide and gold etc.

**Comment by imperator99** [comment]
The only way to do this is to create a new content type that consists of a title, a summary and an external link. On the landing page the card would then reference the external link instead of an internal one. If that is suitable I will go ahead and do it.

**Comment by imperator99** [comment]
@NoniH did you have any comments on the proposed solution?

**Comment by NoniH** [comment]
Yep let's go with that for now

**Comment by NoniH** [comment]
Not needed for the minister but if you have time this would be good to get done. We need it to create the guides landing page.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/177.
Authors can now create 'External links' with a title, summary and external only link. These can be referenced in the 'Related content' field of Landing Page nodes.
