### ISSUE TITLE
Order in menu function not replicated on page

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#105]
<img width="595" alt="screen shot 2018-03-05 at 9 11 03 am" src="https://user-images.githubusercontent.com/21048750/36951224-302ca152-2055-11e8-9b92-64bb8b9d5a03.png">

^^ this order should show up on this vv page
<img width="1011" alt="screen shot 2018-03-05 at 9 11 56 am" src="https://user-images.githubusercontent.com/21048750/36951235-4e4b6240-2055-11e8-8c86-d59a29f454bb.png">

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/124.
