### ISSUE TITLE
Odd things happening on this page (and maybe others too)

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#106]
Things are appearing strangely on the Digital Identity page. https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/37

1. The words "Body content" showing.
2. Introduction not in the right place. (And the word "Introduction" showing.)
3. The "Any questions" section is not for this page.

Screenshot: 

![screen shot 2018-03-05 at 10 18 42 am](https://user-images.githubusercontent.com/19921731/36952065-ef5d4974-205e-11e8-94b9-61aaf2f3320a.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/108.
