### ISSUE TITLE
Text editor does not clean when copying and pasting

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#1066]
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

The text editor is no longer cleaning text when it is copied and pasted from MS word.

**Comment by KiriHoy** [comment]
Removed and reinstalled the format cleaning button for the toolbar. It appears to be working again.
