### ISSUE TITLE
Old blog posts are showing as recent posts

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-website-rebuild#109]
There are 3 posts that are displaying at the top. 

For example:
"Getting inside your head: Analysing search behaviours" is showing up as 2 March 2018 even though I have entered 21 August 2015.

![screen shot 2018-03-05 at 1 32 29 pm](https://user-images.githubusercontent.com/36524570/36955001-d0dea068-2079-11e8-9dac-40ad99e9ba10.png)
![screen shot 2018-03-05 at 1 32 45 pm](https://user-images.githubusercontent.com/36524570/36955002-d117e60c-2079-11e8-810b-7d8df8ea915e.png)

**Comment by imperator99** [comment]
Hi @nicolakcoady the [latest version of the page](https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/167/latest) seems to have the correct date on the full display (21 March 2018). Can you please more that blog into the 'published' state and see if that resolves it? For some reason the view on the home page (and in some other places) is showing the authoring date, not the date date.

**Comment by nicolakcoady** [comment]
@imperator99 looks like the homepage view is fixed now, thanks

**Comment by imperator99** [comment]
Excellent.
