### ISSUE TITLE
Tables are not displaying in a consistent way

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#118]
e.g. on this page
https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/174

we'll need to sort out tables for when we have to publish the annual report etc (very soon)

**Comment by imperator99** [comment]
Gold does not currently have a table style. I have added a basic table style which will have to suffice until something better comes along.

Resolved by https://github.com/govau/dta-gov-au/pull/48.
