### ISSUE TITLE
Can't attach content to parent

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#123]
on this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/117/edit

After moving content to published. I still get this error:

<img width="422" alt="screen shot 2018-03-06 at 8 45 42 am" src="https://user-images.githubusercontent.com/21048750/37001822-d715e642-211b-11e8-9f15-e034ccd531a5.png">

**Comment by imperator99** [comment]
@NoniH You need to make sure you set the 'Change to' state to 'Published' if it already is. What you are trying to do is change the publishing state to 'Draft' at the same time as making the menu changes, so you are still trying to change the menu settings for the draft revision, even if the current revision is published:
![screen shot 2018-03-06 at 9 59 26 am](https://user-images.githubusercontent.com/4567284/37004678-57cf774a-2125-11e8-926d-eea03fa75272.png)

This is a core feature resolving this problem: https://www.drupal.org/project/drupal/issues/2858434.
