### ISSUE TITLE
Side nav display issues

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#128]
Page titles are not lining up and some are being cut off:
<img width="329" alt="screen shot 2018-03-06 at 11 57 47 am" src="https://user-images.githubusercontent.com/21048750/37008370-d027d1a0-2135-11e8-981a-1f84f3434704.png">

**Comment by imperator99** [comment]
They're not lining up because they are child pages. The cutting off is not deliberate though.

**Comment by imperator99** [comment]
I'm unable to replicate this bug, but I have added padding to the inside right of the link to make sure it can't happen.

Resolved by https://github.com/govau/dta-gov-au/pull/50. Style changes will become apparent at the next release.
