### ISSUE TITLE
On small screens "on this page" is defaulting to a drop-down

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#131]
Pretty sure this isn't part of the UI-kit:
<img width="478" alt="screen shot 2018-03-06 at 12 05 41 pm" src="https://user-images.githubusercontent.com/21048750/37008556-c7e423c6-2136-11e8-9533-88186ccf0c81.png">

**Comment by imperator99** [comment]
Seems like a handy feature to me? Is the problem that it is there, or that it isn't styled like GOLD?

**Comment by NoniH** [comment]
The styling... looks very different to the rest of the site

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/49.

Change will be visible after next release.
