### ISSUE TITLE
Contact module not showing up on some pages

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#132]
e.g. https://dta-website-rebuild-develop.apps.y.cld.gov.au/node/123

Contact module for DSS is selected but not showing up on the page

**Comment by imperator99** [comment]
Looks like it is to me:
![screen shot 2018-03-06 at 1 21 48 pm](https://user-images.githubusercontent.com/4567284/37010807-643bbbee-2141-11e8-81eb-e0972508fb29.png)

**Comment by NoniH** [comment]
That's so strange... must have been fixed in the new release
