### ISSUE TITLE
Red box appearing when links are selected

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#136]
If it has to be there at all, can we make it DTA branded? 

This is happening on all active links after they are selected
<img width="1280" alt="screen shot 2018-03-06 at 3 14 12 pm" src="https://user-images.githubusercontent.com/21048750/37013922-25fcb2d8-2151-11e8-99ab-a3eef38e5c16.png">

**Comment by imperator99** [comment]
This is out-of-the-box GOLD functionality for accessibility purposes. It definitely has to be there. I would hesitate to use another colour because it needs to stand out against any possible background, which that colour does.

**Comment by NoniH** [comment]
Ok. I'll let Brie know.
