### ISSUE TITLE
Footer info on News needs padding

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#137]
<img width="614" alt="screen shot 2018-03-06 at 3 19 49 pm" src="https://user-images.githubusercontent.com/21048750/37014022-df662a2e-2151-11e8-8433-0d482c581cf1.png">

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/138 and https://github.com/govau/dta-gov-au/commit/311c3143cde7df219b66408d6c6f4b3c86f5aa4c. Style change will be apparent at the next release window.
