### ISSUE TITLE
Intro text to be the same width as the regular text

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#141]
<img width="825" alt="screen shot 2018-03-06 at 4 21 05 pm" src="https://user-images.githubusercontent.com/21048750/37015378-d5e8caac-215a-11e8-9fb4-0119eba25be2.png">

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/51. Changes will be apparent at the next release window.
