### ISSUE TITLE
Need a way to dictate the size of table cells

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#169]
Especially when there are multiple tables on one page. 

Defaulting to text width won't always work. 

e.g. https://dta-website-rebuild-develop.apps.y.cld.gov.au/about-us/contact-us On this page they are slightly out of whack. 

![screen shot 2018-03-12 at 11 14 52 am](https://user-images.githubusercontent.com/21048750/37260400-c5c82af6-25e6-11e8-8160-d78014fe1bbf.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/170.

Authors can now use the Table tools as well as the right-click contextual menu to adjust cell widths, merge, delete and add columns and rows.

![screen shot 2018-03-13 at 11 26 20 am](https://user-images.githubusercontent.com/4567284/37316116-62e81e0c-26b1-11e8-88e5-9ede41c0e14f.png)

From left to right: new table, delete table, table properties, insert row before, insert row after, delete row, insert column left, insert column right, delete column, insert cell left, insert cell right, delete cell, cell properties, merge cells, merge down, merge right, split horizontally, split vertically.

Commands are also contextually available from the right-click contextual menu.
