### ISSUE TITLE
Straight quotes versus curly quotes

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#172]
When I type a word into the CMS that has an apostrophe or quote mark, it comes out as a straight mark. 

See screen shot: 
![screen shot 2018-03-13 at 10 25 12 am](https://user-images.githubusercontent.com/19921731/37323326-1f96d9a6-26d7-11e8-887b-958643f683b4.png)

The first heading has an apostrophe I typed in, the second one was copied from a Google Doc.

Request: can you make it so that WYSIWYG editing makes the quotes curly? (Noni says we still want to be able to edit HTML to make them straight ones if necessary.)

This explains the difference: https://chrisbracco.com/curly-quotes/

**Comment by imperator99** [comment]
@nigelbartlett the only thing I can find which does this is [this module](https://www.drupal.org/project/typogrify). Can you please check the feature set and let me know if it will do what you want? It does some other things too, but I don't know how useful they are.

In the meantime, there are keyboard shortcuts you can use:

- Opening/closing single quotes: Option + ] / Shift + Option + ]
- Opening/closing double quotes: Option + [ / Shift + Option + [

**Comment by nigelbartlett** [comment]
That module seems to do the trick for the quote marks. The curly ones are "typographer's quotation marks" which is what we want.
I also like the fact that prevents single words wrapping onto their own line.
It's important we fix the quote marks - they stick out like a sore thumb, especially in H1 and H2 headings

**Comment by imperator99** [comment]
Resolved with https://github.com/govau/dta-website-rebuild/pull/188.

@nigelbartlett To create straight quotes, escape the quote by putting a slash before it ie: \' or \". This is in case you need straight marks for imperial measurements or similar.
