### ISSUE TITLE
Search predicting strange words

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#179]
When typing in digital, the search is predicting strange words. Suggest setting prediction to page titles for now if possible. 
![screen shot 2018-03-13 at 3 15 24 pm](https://user-images.githubusercontent.com/21048750/37442569-303f17d4-285b-11e8-9ed0-ffa0a2399e5a.png)

**Comment by imperator99** [comment]
It was the 'stemmer' processor causing this to happen. Turning it off fixes the garbage words returning while maintaining the ability to search for words across the site.
Resolved by https://github.com/govau/dta-website-rebuild/commit/c2390fb1f196e8c50862a1742bd648d1fd597a7c.
