### ISSUE TITLE
Search results need weighting

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#180]
When searching for digital the following results are displayed with #1 not even having digital in the title.

![screen shot 2018-03-15 at 2 13 58 pm](https://user-images.githubusercontent.com/21048750/37442611-759e4764-285b-11e8-9554-d73204dbe36d.png)

Suggest adding the following weighting to search results:
1. Title/H1
2. Summary text
3. H2 
4. Body copy

**Comment by imperator99** [comment]
I have updated the search weightings to reflect the request.
![screen shot 2018-03-19 at 9 54 55 am](https://user-images.githubusercontent.com/4567284/37572196-b2eb4452-2b5b-11e8-8b7d-ce8854baf1c1.png)
Please not the weightings range from 0.0 - 21.0 as per the following:
![screen shot 2018-03-19 at 9 56 19 am](https://user-images.githubusercontent.com/4567284/37572209-d593b912-2b5b-11e8-81bf-cb3c26aec6b7.png)
Resolved by https://github.com/govau/dta-website-rebuild/pull/192.
