### ISSUE TITLE
Remove unnecessary files from repo

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#184]
Since the site is built out by Composer on deploy, there are a lot of things not needed in the repository, such as core, modules, and themes.
Likewise, no need to upload with CF.

**Comment by imperator99** [comment]
Do you think this is done @gordcorp?

**Comment by gordcorp** [comment]
I think there's some more we can remove. Sorry since we've had inconsistent results testing each removal, I've been cautious. I will come back to this and remove one more today

**Comment by gordcorp** [comment]
I think thats the last one I can see...
