### ISSUE TITLE
Inconsistet padding around related content

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#220]
![screen shot 2018-03-22 at 11 52 28 am](https://user-images.githubusercontent.com/21048750/37745186-9618492e-2dc7-11e8-8b5d-26c1f9d2ed4d.png)

On this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/our-projects/digital-identity

**Comment by imperator99** [comment]
Moved to https://github.com/govau/dta-gov-au/issues/93.
