### ISSUE TITLE
Text displaying differently in WYSIWYG compared to on page

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#221]
e.g. this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/listed-degrees-cadetships-and-graduates

Need the text to display as it is in the WYSIWYG not what is currently being displayed on the page.

**Comment by imperator99** [comment]
@NoniH I've updated the HTML filter to allow the <br /> tag through.

However, this is an inappropriate use of the <br /> tag and should actually be formatted as a either a list or as paragraph tags, as the original page is. That wall of text is basically how a visually impaired user will hear the text as <br> is a visual element only and used for addresses or poems which need a visual indicator of lines but actually form a semantic block.

Resolved by https://github.com/govau/dta-website-rebuild/pull/226.
