### ISSUE TITLE
order colouring for associate content vs related content differently 

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#223]
On pages where we use both the automatically populated content AND related content it looks strange that the colours are duplicated. Can we make the automatic colour start from a different one?

<img width="737" alt="screen shot 2018-03-22 at 2 20 58 pm" src="https://user-images.githubusercontent.com/21048750/37749542-7e408aae-2ddc-11e8-94ce-d9008b836081.png">

URL: https://dta-website-rebuild-develop.apps.y.cld.gov.au/about-us

**Comment by imperator99** [comment]
Moved to https://github.com/govau/dta-gov-au/issues/94.
