### ISSUE TITLE
Add <ol> to the filtered HTML list.

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#235]
For some reason `<ol>`s are not included in the filtered HTML list of allowed tags.

**Comment by NoniH** [comment]
Also happening on this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/help-and-advice/digital-service-standard/how-services-are-assessed But seems to be the same issue

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/250.
