### ISSUE TITLE
Grey box elements showing different widths

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#238]
These are two different styling elements but they look strange in different widths. Can we be consistent with our grey boxes? 

![screen shot 2018-04-03 at 10 55 07 am](https://user-images.githubusercontent.com/21048750/38223312-ac7cb208-372d-11e8-8156-94dd840898ef.png)

On this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/help-and-advice/digital-service-standard/services-covered-standard

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/119.
