### ISSUE TITLE
formatting of individual blogs

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-website-rebuild#264]
There are a couple of blogs which need some extra attention in terms of formatting. 

Research recruitment on social media
https://www.dta.gov.au/blog/research-recruitment-on-social-media/
- Leisa's twitter card needs extra formatting

Early Marketplace adoption pays off
https://www.dta.gov.au/blog/early-marketplace-adoption-pays-off/
- video needs drop down transcript

DHS website upgrade project
https://www.dta.gov.au/blog/dhs-website-upgrade-project/
- video needs dropdown transcript

**Comment by nicolakcoady** [comment]
Research recruitment on social media
Fixed

DHS website upgrade project
Fixed

https://beta.dta.gov.au/blogs/research-recruitment-social-media
Card doesn't look the same as the old site but not an urgent fix

**Comment by imperator99** [comment]
Split out into new issues: https://github.com/govau/dta-gov-au/issues/237 and https://github.com/govau/dta-gov-au/issues/238.
