### ISSUE TITLE
Anchor links are anchored too far down the page. 

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#265]
Anchor links should go to the link before the H2 rather than after
![screen shot 2018-04-11 at 11 59 30 am](https://user-images.githubusercontent.com/21048750/38592525-e36b401a-3d7f-11e8-9253-4c9ef3d61b6f.png)

**Comment by imperator99** [comment]
This is not actually a problem, it's the banner covering up the heading. Once https://github.com/govau/dta-website-rebuild/issues/267 is resolved this will not be a problem.
