### ISSUE TITLE
Update banner content

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#277]
On our current site we will say:
 "We're updating our website. [Get a sneak peek](url: new site) of the new site and let us know what you think."

On the new site we will say:
This website is in beta. We’re testing new designs and a small amount of content. Let us know [what you think](url:feedback form). Go back to [dta.gov.au](url: old site)"

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/184.

**Comment by NoniH** [comment]
Hey, can we please add back in the little "go to an external site" icon that we had?
