### ISSUE TITLE
New text in Search box

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#278]
Replace text in Search box with this:

**What are you looking for today?**

However, is it possible to have this search text only on the home page? And then on all the other pages have simply:

**Search dta.gov.au**

If this isn't possible, don't worry about it. :)

Cheers,
Nigel.

**Comment by imperator99** [comment]
Both parts resolved by https://github.com/govau/dta-gov-au/pull/195.
