### ISSUE TITLE
Match contact info on News items with the contact modules across site (from a design perspective)

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#280]
Example: https://dta-website-rebuild-develop.apps.y.cld.gov.au/news/request-feedback-new-software-panel

![screen shot 2018-04-18 at 12 01 15 pm](https://user-images.githubusercontent.com/21048750/38907711-68c5d8f8-4300-11e8-8f8e-5d16ca02ec47.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/208.
