### ISSUE TITLE
Images are distorting if automatically resized to content width

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#281]
e.g. https://dta-website-rebuild-develop.apps.y.cld.gov.au/our-projects/digital-investment-management-office/government-digital-transformation-roadmap

![screen shot 2018-04-18 at 12 42 45 pm](https://user-images.githubusercontent.com/21048750/38909021-1ac954a8-4306-11e8-888f-41ec5c55f22c.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/204.
