### ISSUE TITLE
Filter working poorly on news and blogs page

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#282]
On this page: https://dta-website-rebuild-develop.apps.y.cld.gov.au/news-blogs 

The filter doesn't work very well. Eg, when I type in "ICT procurement" it flashes up the options for only a millisecond and doesn't allow me to click on them. I can only scroll down to them.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/292.
