### ISSUE TITLE
Quotes need styling

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#301]
Not sure what we landed on with Matt but I'm pretty sure it wasn't this
<img width="852" alt="screen shot 2018-04-20 at 9 20 22 pm" src="https://user-images.githubusercontent.com/21048750/39048403-a909a732-44e0-11e8-813b-335082ab0e5c.png">

Example from: https://beta.dta.gov.au/news/digital-marketplace-your-feedback-counts

**Comment by imperator99** [comment]
I implemented the design for pullquotes pretty much as specified:
![pullquote](https://user-images.githubusercontent.com/4567284/39079407-65bb7fdc-455d-11e8-9a17-7ff9b163daf2.png)
