### ISSUE TITLE
Caption error

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#307]
The IP Australia blog is showing two colons but there's none in the text field:
https://beta.dta.gov.au/blogs/guest-blog-ip-australias-award-winning-search-tool

<img width="843" alt="screen shot 2018-04-22 at 8 59 38 am" src="https://user-images.githubusercontent.com/21048750/39089507-c3b21386-460b-11e8-96ea-3b1f217e1c41.png">
<img width="911" alt="screen shot 2018-04-22 at 8 59 22 am" src="https://user-images.githubusercontent.com/21048750/39089508-c3df6e26-460b-11e8-9a6f-611a72400161.png">

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/308.
