### ISSUE TITLE
Make a node for News/Blogs page

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#324]
The News/Blogs page doesn't appear to be a node. (I can't link to it from other pages.) Can you make it a node?

This page: https://beta.dta.gov.au/news-blogs

**Comment by imperator99** [comment]
@nigelbartlett just use the URL without the domain in the link field, ie `/news-blogs`. That URL will never change because it is created by a View so it is safe to link to like that. As long as you don't add the domain to the start, ie `https://beta.dta.gov.au/news-blogs` it'll be OK.
