### ISSUE TITLE
Update media contact box

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#356]
The Get in Touch box for media enquiries seems to be hard-coded.

Is there a way that this can be a module that I can edit myself?

In the meantime, please replace this text:

For media enquiries, email us at media@digital.gov.au

With this text:

For media enquiries email us at media@digital.gov.au

(ie: take out the comma)

**Comment by imperator99** [comment]
FYI it is hardcoded as per [this issue](https://github.com/govau/dta-website-rebuild/issues/126) from a Slack request. I will update.

**Comment by imperator99** [comment]
@nigelbartlett Yes I think it probably can be un-hard-coded. I'll look into it and let you know.

**Comment by imperator99** [comment]
@nigelbartlett I have added this functionality to the test site. Can you please check whether it works as you expect?

1. Head to the test site.
2. Note updated text on any news item page (for example, /news/abluo-meus-voco).
3. Go to the content listing page and find the 'Media Enquiries' item. It is of type 'home page'. Its URL is /node/397.
4. Update the text, and publish as per usual.
5. Go back to any news item and confirm the text has changed.

**Comment by nigelbartlett** [comment]
Great - that works perfectly. Thanks @imperator99

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/362.
