### ISSUE TITLE
How to show Alpha, Beta, Live tags on a list of assessment reports

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#363]
On the old dta.gov.au we have a list of DSS assessment reports labelled with coloured tags according to whether the service is Alpha, Beta or Live (see attached screenshot).

Is there a similar solution we can find for the new website? (New page, not published yet: https://beta.dta.gov.au/assessment-reports)

Jesse: before you start work on this ticket, have a chat with me as I'm not sure how much of a priority this page is. So if it's going to be a lot of work for you, might not be worth it. If it's an easy fix, then it could be worth doing.

![screen shot 2018-05-15 at 9 12 32 am](https://user-images.githubusercontent.com/19921731/40028089-67323d12-5820-11e8-9a3b-db5ac6d56806.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/451.
