### ISSUE TITLE
Difficulty getting the "Get in touch" module to work on some pages

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#364]
- [ ] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [ ] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [ ] I’ve searched for any related issues and avoided creating a duplicate issue.

Not sure what's going on here, but a few pages I work on refuse to show the Get In Touch module after I've added it - even if I wait overnight and check the next morning. (I asked Noni to have a look too but she couldn't see it.)

Here's the latest page where this is happening for me: https://beta.dta.gov.au/assessment-reports

**Comment by imperator99** [comment]
This no longer seems to be an issue.
