### ISSUE TITLE
Language filter

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#41]
Perhaps remove or simplify?

**Comment by imperator99** [comment]
@NoniH Can you please elaborate on what this refers to?

**Comment by NoniH** [comment]
![screen shot 2018-01-22 at 11 06 43 am](https://user-images.githubusercontent.com/21048750/35200535-74951b38-ff64-11e7-9be2-00f577d112c9.png)

See image

**Comment by imperator99** [comment]
Language filter has been removed.
Resolved by https://github.com/govau/dta-website-rebuild/commit/6adb517ff7cca60485033d930dd4779aeb0820bb.
