### ISSUE TITLE
`run-task` should not have side-effects unless task explicitly wants them

### ISSUE THREAD

**Issue by aeijdenberg** [govau/dta-website-rebuild#442]
Running `cf run-task <appname> "drush ..."` executes https://github.com/govau/dta-website-rebuild/blob/develop/scripts/preprocess.sh before running the specified command.

While the `preprocess.sh` script can be useful for setting up environment and other local config it should not do anything (such as database updates or external cache rebuilds) that have side-effects outside of the container that it runs in.

Consider moving the current database update and other code to the start script.

This will make it much easier and safer to run administrative commands on the system when needed.

**Comment by gordcorp** [comment]
Noting that the [buildpack doco](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#options) says about preprocess:
> A list of additional commands that run prior to the application starting. For example, you might use this command to run migration scripts or static caching tools before the application launches.

Maybe we just need to change so its safer to run tasks.

/shrug

**Comment by imperator99** [comment]
Possibly resolved by https://github.com/govau/dta-website-rebuild/pull/449, which adds extra checks to ensure a cache rebuild occurs only when necessary. Manual cache rebuilds can of course still be used.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/449.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/456.
