### ISSUE TITLE
Plugin config settings and database migration scripts

### ISSUE THREAD

**Issue by aeijdenberg** [govau/dta-website-rebuild#444]
We have manually set various config settings for `login_security` in both prod and staging, and then called `updatedb` to complete the migration scripts.

If we instead left this to the startup script, it would have imported config first (overwriting those settings) and then call the migration scripts which failed.

Opening this issue to track putting the correct values back into the files in source control, and further determining what the correct process is for a database config upgrade.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/452. This includes correct config for `login_security`.

The issue with `updatedb` not completing for this module has been resolved by simply uninstalling and reinstalling the module.

Further, broken database schema updates will not result in a deployment, as per https://github.com/govau/dta-website-rebuild/pull/449.
