### ISSUE TITLE
Database migrate failures should prevent app from starting

### ISSUE THREAD

**Issue by aeijdenberg** [govau/dta-website-rebuild#445]
Currently if a database migration script fails the app will still start successfully, although we note sometimes it remains in maintenance mode.

It would be more helpful if a migrate failure would stop the app from starting successfully, as in this way a blue-green deploy would simply fail to deploy rather than mask the error in staging which may not be seen until encountered due to an unattended application restart in production (which occasionally, but curiously not always, seems to keep the app in maintenance mode).

**Comment by imperator99** [comment]
A possible solution is to abort the deployment if the response from `drush updatedb` contains an error, then abort the deployment.

**Comment by imperator99** [comment]
That's what I thought too, but it seems to have regressed since: https://github.com/drush-ops/drush/issues/3376. Certainly, when I run `drush updatedb -y` and the `echo $?` I always get back `0`, even if the update 'fails'.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/449.
