### ISSUE TITLE
Index images - all content types

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#45]
Ad index images as an option to all pages (not mandatory)

To display on landing page listings, search results or anywhere the content is pulled

**Comment by imperator99** [comment]
@NoniH is this the same as a 'thumb' image?

**Comment by NoniH** [comment]
Yeah I think so. Isn't it called index image in the CMS?

**Comment by imperator99** [comment]
You can call it whatever you want. 'Index image' is fine. I think, like 'lede', 'thumb' is a bit domain-specific.

**Comment by imperator99** [comment]
New 'index image' field is in the site. Currently displays on 'teaser' display modes only. Accepts 450x300 images only with a 20KB maximum. This will change when the page design is clearer.
Resolved by https://github.com/govau/dta-website-rebuild/commit/97d9347949aa65302c3be662a8dd7ee34a87176d.
