### ISSUE TITLE
Page title should be limited to 65 characters

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#46]
Explain this limitation in the field information.

**Comment by imperator99** [comment]
There are various modules that might accomplish this behaviour. Node titles are a tricky thing to work with as they don't work as regular fields. I will try [Node Title Validation](https://www.drupal.org/project/node_title_validation) and see if that works. If it is a common use case for DTA (and other Government) sites then this will be a useful addition.

**Comment by imperator99** [comment]
The [Node Title Help Text](https://www.drupal.org/project/node_title_help_text) module will enable administrators to add help text to node titles. Again, if this is a common use case for the DTA then this will be a useful addition.

**Comment by imperator99** [comment]
A patch was required to ensure that Node Title Validation exported and imported its configuration properly.
Resolved by https://github.com/govau/dta-website-rebuild/commit/affd2ceee4e7c7550ceefb76c325eb6dcbf5db51, https://github.com/govau/dta-website-rebuild/commit/549e6aed1bfd02b39306a52eb121c8bb36d846f3 and https://github.com/govau/dta-website-rebuild/commit/5e0498ec6ae2dead5fcb3e357412ba5d0abb1323.

**Comment by imperator99** [comment]
Another patch was required to prevent issues with the 'prevent duplicate node titles' part of the Node Title Validation module. Resolved by https://github.com/govau/dta-website-rebuild/commit/9ad7237e8024a3ce2b4a6a9ee20d40ec597bf1ee.
