### ISSUE TITLE
Make all metadata "required"

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#47]
Add text as to why it's required.

**Comment by NoniH** [comment]
From an author's perspective it should be: Title and Summary
For blogs (and any tagged content) we should also make adding tags mandatory - so that Authors can't make that mistake.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/commit/c99edafcdcb9eedb06dd5cfc35773df5c5956921. All 'Summary' and 'Tags' fields are mandatory.
