### ISSUE TITLE
Option to add social images for all pages

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#48]
Every page type to have social image options and hero image options. Whether they are used or not will depend on the team. 

Including info for size and ratio requirements.

**Comment by imperator99** [comment]
Updated image options for 'basic page' content type. Core content types (news, blog and page) all now have the same image fields. Resolved by https://github.com/govau/dta-website-rebuild/commit/8ff644b686a26187487bc49eade3eb886404019f and https://github.com/govau/dta-website-rebuild/commit/489460cb644135a78bca27c944d52bb7d54d76d5.
