### ISSUE TITLE
Add additional image in body text

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#50]
Couldn't work out how to upload an image to add in the body text – all pages

**Comment by imperator99** [comment]
The file manager was not set up correctly. It has been fixed and content editors can now use the upload function. Edit the image by double clicking on it once it has been added to the page.
Resolved by https://github.com/govau/dta-website-rebuild/commit/eb757dfcbf7fe1f9cf803af03a59997a297ade07.
