### ISSUE TITLE
Adjust summary placement and description

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#51]
Indicate where the summary text will be displayed. 

i.e. "To be displayed in search results and page listings"

Make field always visible and move to after the body text (as it's metadata not the introduction)

**Comment by imperator99** [comment]
This requires changing how the default 'long text with summary' functions. It is essentially one field with two separate places to store text. I have no way of altering the order in which they display at this point without writing a custom module. 
The only solution currently available is to replace the existing body field with two separate fields, a body field and a summary field.
It is fortunate that there is very little content in the site, as this is a difficult procedure. I will create the new fields and and copy the text over. It will also require adjustment of the display modes for each content type to ensure the new fields are displaying.
Once the site has more content this kind of operation will become more and more difficult, so please be aware this is not something that can happen often.

**Comment by imperator99** [comment]
Body and summary pages have been separated. There are now two new fields, Summary (field_summary) and 'Body content' (field_body). Display modes and forms have been adjusted to take the new fields into account. The out-of-the-box body field has been removed. See https://github.com/govau/dta-website-rebuild/commit/33fc0fc5ca104d2e607526b2a039d7197c8434d4.

**Comment by imperator99** [comment]
Summary help text has been added by https://github.com/govau/dta-website-rebuild/commit/7baa5d26e7f83653b5ee6d25a325629aef788598.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/commit/33fc0fc5ca104d2e607526b2a039d7197c8434d4 and https://github.com/govau/dta-website-rebuild/commit/7baa5d26e7f83653b5ee6d25a325629aef788598.
