### ISSUE TITLE
Simple, clear and fast public services - single line vs split onto 2 lines

### ISSUE THREAD

**Issue by Sarah-Cr** [govau/dta-website-rebuild#586]
The text 'Simple, clear and fast public services' is displayed differently on the homepage vs sub-pages. Is this on purpose and does it matter?

![simple clear fast child](https://user-images.githubusercontent.com/25679296/48744538-bdabea00-ecbb-11e8-96a3-af712a22a807.JPG)
![simple clear fast home](https://user-images.githubusercontent.com/25679296/48744540-bdabea00-ecbb-11e8-8a91-83dacd0baa6e.JPG)

**Comment by imperator99** [comment]
Hi @Sarah-Cr this was done on purpose to create a visual distinguishment (?) between the home page and the rest of the site. There also used to be stuff in the right hand side.
