### ISSUE TITLE
card text running into arrow

### ISSUE THREAD

**Issue by Sarah-Cr** [govau/dta-website-rebuild#588]
![cards](https://user-images.githubusercontent.com/25679296/48750658-5a7a8180-ecd4-11e8-9801-876504c4bffa.JPG)

Problem shown in image.

**Comment by imperator99** [comment]
@Sarah-Cr this seems to have been resolved by https://github.com/govau/dta-website-rebuild/pull/624 which had the effect of making the cards substantially larger.

Let me know if you see it on any other pages.
