### ISSUE TITLE
Main nav active item loses focus when on children pages

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/dta-website-rebuild#592]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What happened

Not sure if this is intended but when I visit children pages of the main nav links, the main nav link loses its active state CSS ( the white underline on active link)

## Steps to reproduce:

1. Go to https://www.dta.gov.au/about-us
2. Click any of the link in the side nav
3. The about link in main nav loses underline

# Screenshots

![image](https://user-images.githubusercontent.com/20184809/48755117-5193ab00-ece8-11e8-8e68-4b07e2c2d72d.png)

**Comment by imperator99** [comment]
@sukhrajghuman Looks like there's no style set for the CSS selector which gets applied to the active trail for the Superfish menu. Thanks for pointing it out.

Does this test sum it up for you?

1. Given that I am on https://www.dta.gov.au/about-us
2. When I visit the first link in `#block-mainnavigation-3`
3. Then the `About us` link in `#superfish-main` should have the `active-trail` class applied and be underlined in white.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/releases/tag/1.8.6 and https://github.com/govau/dta-website-rebuild/pull/639
