### ISSUE TITLE
Circle icon in the search box?

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/dta-website-rebuild#603]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

Not sure what the circle icon is at the end of the search box? Is it supposed to be a magnify glass?

![image](https://user-images.githubusercontent.com/20184809/48819631-0d1a1500-eda5-11e8-9d56-478a6ee770f4.png)

**Comment by imperator99** [comment]
It indicates an ajax procedure. If you start typing in the search box it starts doing things.
