### ISSUE TITLE
Landing page content type

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#61]
The site requires a content type for landing pages.

**Comment by NoniH** [comment]
"a content area at the top for an introductory sentence or two, and then I will place a 'View' of dynamic content on there in the back end, using the menu structure."

Can you check with Matt of there are any other requirements? Perhaps have a look at the help and advice mockup that he did

**Comment by NoniH** [comment]
![screen shot 2018-02-13 at 12 07 41 pm](https://user-images.githubusercontent.com/21048750/36128448-871c976e-10b6-11e8-8e0b-5456133a3581.png)

**Comment by NoniH** [comment]
Needs:
 - All metadata (summary text, tag options etc)
 - Title
 - Intro
 - Body
 - Card listing
 - ability to add images into the body text and metadata as an option

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/commit/c34298927019ef8f4120ac66e10e8c09e44db9cb.
