### ISSUE TITLE
Design a way to archive blog and news posts that are older than a year old

### ISSUE THREAD

**Issue by Sarah-Cr** [govau/dta-website-rebuild#619]
It would be good to only display blog and news from the last year on the index page. Anything older can still be found if searched but it's clear that they're archived.

**Comment by imperator99** [comment]
@Sarah-Cr I can see a couple of pieces of functionality here:

1. The index page is limited to anything published in the last year (current).
2. There's a new index page for items older than that, called 'Archive' or similar.
3. There would be some text on the current index page saying the archive exists if the user needs it.
4. There would be text on the archive index page indicating why these items are there and a link back to the current index page.

Other than that, functionally the current index and the archive index pages would be the same. Archived items would still be in the search index too.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/644.
