### ISSUE TITLE
BUG: unable to upload thumbnail image from old blogs

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#62]
<img width="808" alt="screen shot 2018-02-13 at 5 00 30 pm" src="https://user-images.githubusercontent.com/21048750/36135495-9f07b06a-10df-11e8-9ac6-24ea10a90e80.png">
When trying to upload an old blog post using the same images from the old post, I get this error of the thumbnail image only.

**Comment by NoniH** [comment]
I need to be able to just use the same images if possible

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/commit/5365aa85459762506fd1e73790fe63a8f6b6c360.

Index image field has been updated to decrease minimum size to 300x200px. Existing blog thumbnails are 400x267px.
