### ISSUE TITLE
Redirect old site link structure to new structure

### ISSUE THREAD

**Issue by adamzerella** [govau/dta-website-rebuild#621]
- [x] I’ve read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## Steps to reproduce:
Search something like `dta blog certificate transparency` in a private browsing window and you'll probably see the top link for this search result is a 404 on the www.dta.gov.au site.

**Old structure** - https://www.dta.gov.au/blog/building-trust-with-certificate-transparency/ 
**New structure** - https://www.dta.gov.au/blogs/buckle-browser-changes-ahead

I'm assuming a lot of the links from the previous dta site that were indexed by search engines will face this type of issue. 

Perhaps forcing a recrawl or redirecting old blog links like `https://www.dta.gov.au/blogs/page-title-here` to `https://www.dta.gov.au/blog/page-title-here` would resolve this.

# Screenshots

Search: ![image](https://user-images.githubusercontent.com/1501560/49058785-a8096800-f259-11e8-9e34-d4224bf3d374.png)

Link: 
![image](https://user-images.githubusercontent.com/1501560/49058803-b788b100-f259-11e8-8cf7-69304eb12f78.png)

**Comment by imperator99** [comment]
Thanks @adamzerella. I've forced a recrawl of the site but that can take a while. In the meantime I've added a redirect for that page specifically. The instances of broken searches will reduce over time.

If you find any other broken links or search results please let me know and I will repair them.
