### ISSUE TITLE
Add <hr> function in body copy to indicate a change in content

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#63]
In this blog: https://www.dta.gov.au/blog/security-operation-centre-myths/

We use a horizontal rule tag to create a line. This allows us to indicate that the text below is not part of the blog. 

I tried to do the same thing when copying over the blog and the source function wouldn't let me do it.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/commit/1179a1d145f848a881cd6185d81dd9a41152ba3a.

The <hr> tag is now available in the WYSIWYG.
