### ISSUE TITLE
BUG: when pasting "normal" content from google docs, content automatically is bolded

### ISSUE THREAD

**Issue by NoniH** [govau/dta-website-rebuild#65]
This is happening for all WYSIWYG fields on a page.

**Comment by imperator99** [comment]
Can you try using the 'paste from word' function (the clipboard with the 'w' on it)? This is an issue with Google Docs/Chrome preserving all HTML associated with a document when it copies and pastes.

**Comment by NoniH** [comment]
![screen shot 2018-02-14 at 12 04 36 pm](https://user-images.githubusercontent.com/21048750/36182761-4b94b52c-117f-11e8-8025-13f8c8949886.png)

I get this when I select the past from word button

**Comment by imperator99** [comment]
Closing this for now - seems to be an issue with Google Docs rather than with the CMS. Authors will need to be made aware of it.
