### ISSUE TITLE
Required field should only validate when tabbing out of it

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/dta-website-rebuild#683]
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

The required email field is distracting. It should only activate when a user clicks in it and then tabs out. If I visit an [article page](https://www.dta.gov.au/news/blockchain-latest-advice-government-agencies) for example, it takes away the attention from the article and makes me feel like I've done something wrong.

![image](https://user-images.githubusercontent.com/20184809/52606047-4a360500-2ec5-11e9-851a-23494947473d.png)

One way of doing that is adding a class to the text input that resets the invalid styling. 

So something like: 

```css 
.empty-required {
    background: transparent;
    border-color: gray;
}
```

And then removing that class  using javascript `onBlur` event

**Comment by imperator99** [comment]
Thanks @sukhrajghuman I'll look into this. The actual field set up is brought directly over from MailChimp and I hadn't thought to adjust it.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/765
