### ISSUE TITLE
How tagging and search works

### ISSUE THREAD

**Issue by nicolacoady** [govau/dta-website-rebuild#695]
When tagging content, does it work with the search function? Eg - if lots of people are searching google and the DTA website for govpass but we don't mention govpass on our website, could we tag the digi ID content with govpass so people can find the right content?

**Comment by imperator99** [comment]
It seems like I can adjust the search index display to include tags which should then make sure it is included in the search results more easily.

**Comment by imperator99** [comment]
Resolved by:
- https://github.com/govau/dta-website-rebuild/pull/707
- https://github.com/govau/dta-website-rebuild/pull/704
- https://github.com/govau/dta-website-rebuild/pull/703
- https://github.com/govau/dta-website-rebuild/pull/699
