### ISSUE TITLE
Google summary needs updating for subscribe to mailing list

### ISSUE THREAD

**Issue by nicolacoady** [govau/dta-website-rebuild#696]
Not a big issue but when I search for DTA subscribe blog in google it says I can choose what I subscribe to, but that isn't the case anymore right?

![subscribe summary](https://user-images.githubusercontent.com/20121793/53848748-a7772f00-4009-11e9-866e-4bfd520607c8.jpg)

**Comment by imperator99** [comment]
Thanks Nicola. This is actually coming from the old site. If you were to click the link it goes directly to the new site. I don't know what else I can actually do to stop this happening but I will keep looking into it.
