### ISSUE TITLE
Card content being cut off

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/dta-website-rebuild#811]
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

The cards on the [content design](https://www.dta.gov.au/taxonomy/term/52) page are being cut off. This is because they have a height that is fixed at 28rem. Since this is using flex I would recommend removing this fixed height and let flex do it's magic.

![image](https://user-images.githubusercontent.com/20184809/62588968-07e90000-b90b-11e9-8f66-699d3ccf4ab4.png)

You may run into the problem of having lots of white space such as below:

![image](https://user-images.githubusercontent.com/20184809/62589071-68783d00-b90b-11e9-9093-44b24b01f7fa.png)

This could be resolved by reducing the text size or reducing the amount of content in each of these cards.

**Comment by imperator99** [comment]
Thanks @sukhrajghuman!
You're not actually supposed to be seeing that page so I have redirected requests to go to the blogs page with it pre-filtered.
Thanks!
