### ISSUE TITLE
Blog posts showing on landing pages

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#95]
Blog posts are showing up as cards on landing pages. Eg: the card on the left on this page below.

![screen shot 2018-03-01 at 10 21 06 am](https://user-images.githubusercontent.com/19921731/36818779-b7b7f46e-1d3a-11e8-82b9-88bc9c658f39.png)

**Comment by NoniH** [comment]
+1 for this issue.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/110.
