### ISSUE TITLE
Can't update status on Learning and Development landing page

### ISSUE THREAD

**Issue by nigelbartlett** [govau/dta-website-rebuild#96]
For some reason I couldn't update the status to "Published" on the Learning and Development landing page. (I ended up doing it from the content listing page.)

Here's the screen shot, which shows that the status is missing:

![screen shot 2018-03-01 at 11 07 48 am](https://user-images.githubusercontent.com/19921731/36820338-773d22cc-1d41-11e8-8fe2-781b31f9edbd.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/122.
