### ISSUE TITLE
Text falling off screen - Mobile responsiveness

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/dta-website-rebuild#970]
1. Go to https://www.dta.gov.au/our-projects/about-domainnamegovau on a smaller device
2. The `<h1>` element is going off the screen.

![image](https://user-images.githubusercontent.com/20184809/74991523-448cdb00-549a-11ea-93b5-fabc632f3ac9.png)

![image](https://user-images.githubusercontent.com/20184809/74991583-65edc700-549a-11ea-8d22-e49b7d2a696e.png)

From a quick 30 second inspection, I'm not sure what's causing it. If I figure it out will post it here

**Comment by imperator99** [comment]
Thanks @sukhrajghuman I suppose it is because it is an extra long word (because of the full stops) and so it's not breaking. Might have to do some CSS trickery to fix it - or remove the URL from the heading.

**Comment by sukhrajghuman** [comment]
@imperator99 Yep you are right, it's because its a long word.
I think adding using the `word-break` property will fix it.

**Comment by KiriHoy** [comment]
Fixed in #1018
