### ISSUE TITLE
Blog author by lines should be italicised

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#985]
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

# What is the context for your issue or request?

When I navigate to a blog page

# What action do you want to take within that context?

And I scroll to the bottom

# What do you expect to happen when you take that action?
Then I should see the author byline and it should be separated from the main body of the text.

**Comment by KiriHoy** [comment]
fixed in #1010
