### ISSUE TITLE
Fix 'Back to top' link on home page

### ISSUE THREAD

**Issue by imperator99** [govau/dta-website-rebuild#987]
- [x] I’ve read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

Now that we have re-arranged the home page, we also need to update the appearance of the 'back to top' link.

<img width="622" alt="Screen Shot 2020-03-30 at 4 11 41 pm" src="https://user-images.githubusercontent.com/4567284/77877368-50da3400-72a1-11ea-957f-cea2824e6e1d.png">

**Comment by KiriHoy** [comment]
Fixed by #991
